name: CI for CI/CD Project

on :
  push:
    branches: [main]
  pull_request:
    branches: [main]

  jobs: 
    hello-world:
      runs-on: ubuntu-latest
      
      steps:
      - name: Chekout code
      - uses: actions/checkout@v3

      - name: Say Hallo
      - run: echo "Hello, GitHub Actions! Im really VERY HAPPY! This is my first workflow!

      - name: Show date
        run: date
